"""update_vector_dim

Revision ID: 8cdffe164ead
Revises: 210885f3050d
Create Date: 2025-12-29 11:12:16.275907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '8cdffe164ead'
down_revision: Union[str, Sequence[str], None] = '210885f3050d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'embedding',
               existing_type=Vector(1536),
               type_=Vector(384),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'embedding',
               existing_type=Vector(384),
               type_=Vector(1536),
               existing_nullable=True)
    # ### end Alembic commands ###
